/****************************************************************************
 * Copyright (C) 2025 Xiaomi Corporation
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __VENDOR_FLAGCHIP_CHIPS_FC7300_CHIP_H
#define __VENDOR_FLAGCHIP_CHIPS_FC7300_CHIP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

/* Include the memory map and the chip definitions file.
 * Other chip hardware files should then include this file for the proper
 * setup.
 */

#include <arch/irq.h>
#include "hardware/fc7300_memorymap.h"

/* If the common ARMv7-M vector handling logic is used, then it expects
 * the following definition in this file that provides the number of
 * supported vectors external interrupts (which for the FC7300 is the same
 * as the number of peripheral identifiers).
 */

#define ARMV7M_PERIPHERAL_INTERRUPTS FC7300_IRQ_NEXTINT

/* Cache line sizes (in bytes)for the FC7300 */

#define ARMV7M_DCACHE_LINESIZE 16  /* 16 bytes (4 words) */
#define ARMV7M_ICACHE_LINESIZE 16  /* 16 bytes (4 words) */

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Default ADCx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_ADC0)
#  define NVIC_ADC0_PRIORITY_DEFAULT       CONFIG_FC7300_ADC0_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_ADC1)
#  define NVIC_ADC1_PRIORITY_DEFAULT       CONFIG_FC7300_ADC1_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_ADC2)
#  define NVIC_ADC2_PRIORITY_DEFAULT       CONFIG_FC7300_ADC2_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_ADC3)
#  define NVIC_ADC3_PRIORITY_DEFAULT       CONFIG_FC7300_ADC3_ISR_PRIORITY
#endif
# else
#  define NVIC_ADC0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ADC1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ADC2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ADC3_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default FTUx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_FTU0_CAP)
#  define NVIC_FTU0_PRIORITY_DEFAULT       CONFIG_FC7300_FTU0_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU1_CAP)
#  define NVIC_FTU1_PRIORITY_DEFAULT       CONFIG_FC7300_FTU1_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU2_CAP)
#  define NVIC_FTU2_PRIORITY_DEFAULT       CONFIG_FC7300_FTU2_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU3_CAP)
#  define NVIC_FTU3_PRIORITY_DEFAULT       CONFIG_FC7300_FTU3_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU4_CAP)
#  define NVIC_FTU4_PRIORITY_DEFAULT       CONFIG_FC7300_FTU4_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU5_CAP)
#  define NVIC_FTU5_PRIORITY_DEFAULT       CONFIG_FC7300_FTU5_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU6_CAP)
#  define NVIC_FTU6_PRIORITY_DEFAULT       CONFIG_FC7300_FTU6_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU7_CAP)
#  define NVIC_FTU7_PRIORITY_DEFAULT       CONFIG_FC7300_FTU7_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU8_CAP)
#  define NVIC_FTU8_PRIORITY_DEFAULT       CONFIG_FC7300_FTU8_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU9_CAP)
#  define NVIC_FTU9_PRIORITY_DEFAULT       CONFIG_FC7300_FTU9_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU10_CAP)
#  define NVIC_FTU10_PRIORITY_DEFAULT      CONFIG_FC7300_FTU10_CAP_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FTU11_CAP)
#  define NVIC_FTU11_PRIORITY_DEFAULT      CONFIG_FC7300_FTU11_CAP_ISR_PRIORITY
#endif
#else
#  define NVIC_FTU0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU3_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU4_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU5_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU6_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU7_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU8_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU9_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU10_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FTU11_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default IICx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_FCIIC0)
#  define NVIC_IIC0_PRIORITY_DEFAULT       CONFIG_FC7300_FCIIC0_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FCIIC1)
#  define NVIC_IIC1_PRIORITY_DEFAULT       CONFIG_FC7300_FCIIC1_ISR_PRIORITY
#endif
#else
#  define NVIC_IIC0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_IIC1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default ERM isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_ERM)
#  define NVIC_ERM_PRIORITY_DEFAULT        CONFIG_FC7300_ERM_ISR_PRIORITY
#endif
#else
#  define NVIC_ERM_PRIORITY_DEFAULT        NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default FCSMU isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_FCSMU)
#  define NVIC_FCSMU_PRIORITY_DEFAULT      CONFIG_FC7300_FCSMU_ISR_PRIORITY
#endif
#else
#  define NVIC_FCSMU_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default CMUx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_CMU0)
#  define NVIC_CMU0_PRIORITY_DEFAULT       CONFIG_FC7300_CMU0_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_CMU1)
#  define NVIC_CMU1_PRIORITY_DEFAULT       CONFIG_FC7300_CMU1_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_CMU2)
#  define NVIC_CMU2_PRIORITY_DEFAULT       CONFIG_FC7300_CMU2_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_CMU3)
#  define NVIC_CMU3_PRIORITY_DEFAULT       CONFIG_FC7300_CMU3_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_CMU4)
#  define NVIC_CMU4_PRIORITY_DEFAULT       CONFIG_FC7300_CMU4_ISR_PRIORITY
#endif
#else
#  define NVIC_CMU0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_CMU1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_CMU2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_CMU3_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_CMU4_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default PMC isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_PMC)
#  define NVIC_PMC_PRIORITY_DEFAULT        CONFIG_FC7300_PMC_ISR_PRIORITY
#endif
#else
#  define NVIC_PMC_PRIORITY_DEFAULT        NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default TMU isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_TMU)
#  define NVIC_TMU_PRIORITY_DEFAULT        CONFIG_FC7300_TMU_ISR_PRIORITY
#endif
#else
#  define NVIC_TMU_PRIORITY_DEFAULT        NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default MAMx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_MAM)
#  define NVIC_MAM0_PRIORITY_DEFAULT       CONFIG_FC7300_MAM0_ISR_PRIORITY
#  define NVIC_MAM1_PRIORITY_DEFAULT       CONFIG_FC7300_MAM1_ISR_PRIORITY
#  define NVIC_MAM2_PRIORITY_DEFAULT       CONFIG_FC7300_MAM2_ISR_PRIORITY
#endif
#else
#  define NVIC_MAM0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_MAM1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_MAM2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default FLEXCANx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_FLEXCAN0)
#  define NVIC_FLEXCAN0_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN0_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN1)
#  define NVIC_FLEXCAN1_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN1_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN2)
#  define NVIC_FLEXCAN2_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN2_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN3)
#  define NVIC_FLEXCAN3_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN3_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN4)
#  define NVIC_FLEXCAN4_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN4_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN5)
#  define NVIC_FLEXCAN5_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN5_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN6)
#  define NVIC_FLEXCAN6_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN6_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN7)
#  define NVIC_FLEXCAN7_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN7_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN8)
#  define NVIC_FLEXCAN8_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN8_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_FLEXCAN9)
#  define NVIC_FLEXCAN9_PRIORITY_DEFAULT   CONFIG_FC7300_FLEXCAN9_ISR_PRIORITY
#endif
#else
#  define NVIC_FLEXCAN0_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN1_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN2_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN3_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN4_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN5_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN6_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN7_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN8_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_FLEXCAN9_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default LINx isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_LIN0)
#  define NVIC_LIN0_PRIORITY_DEFAULT       CONFIG_FC7300_LIN0_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN1)
#  define NVIC_LIN1_PRIORITY_DEFAULT       CONFIG_FC7300_LIN1_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN2)
#  define NVIC_LIN2_PRIORITY_DEFAULT       CONFIG_FC7300_LIN2_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN3)
#  define NVIC_LIN3_PRIORITY_DEFAULT       CONFIG_FC7300_LIN3_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN4)
#  define NVIC_LIN4_PRIORITY_DEFAULT       CONFIG_FC7300_LIN4_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN5)
#  define NVIC_LIN5_PRIORITY_DEFAULT       CONFIG_FC7300_LIN5_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN6)
#  define NVIC_LIN6_PRIORITY_DEFAULT       CONFIG_FC7300_LIN6_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN7)
#  define NVIC_LIN7_PRIORITY_DEFAULT       CONFIG_FC7300_LIN7_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN8)
#  define NVIC_LIN8_PRIORITY_DEFAULT       CONFIG_FC7300_LIN8_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN9)
#  define NVIC_LIN9_PRIORITY_DEFAULT       CONFIG_FC7300_LIN9_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN10)
#  define NVIC_LIN10_PRIORITY_DEFAULT      CONFIG_FC7300_LIN10_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN11)
#  define NVIC_LIN11_PRIORITY_DEFAULT      CONFIG_FC7300_LIN11_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN12)
#  define NVIC_LIN12_PRIORITY_DEFAULT      CONFIG_FC7300_LIN12_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN13)
#  define NVIC_LIN13_PRIORITY_DEFAULT      CONFIG_FC7300_LIN13_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN14)
#  define NVIC_LIN14_PRIORITY_DEFAULT      CONFIG_FC7300_LIN14_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN15)
#  define NVIC_LIN15_PRIORITY_DEFAULT      CONFIG_FC7300_LIN15_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN16)
#  define NVIC_LIN16_PRIORITY_DEFAULT      CONFIG_FC7300_LIN16_ISR_PRIORITY
#endif
#if defined(CONFIG_FC7300_LIN17)
#  define NVIC_LIN17_PRIORITY_DEFAULT      CONFIG_FC7300_LIN17_ISR_PRIORITY
#endif
#else
#  define NVIC_LIN0_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN3_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN4_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN5_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN6_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN7_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN8_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN9_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN10_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN11_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN12_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN13_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN14_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN15_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN16_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_LIN17_PRIORITY_DEFAULT      NVIC_SYSH_PRIORITY_DEFAULT
#endif

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_PORTAINTS
#  define NVIC_PORTA_PRIORITY_DEFAULT         CONFIG_FC7300_PORTA_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTBINTS
#  define NVIC_PORTB_PRIORITY_DEFAULT         CONFIG_FC7300_PORTB_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTCINTS
#  define NVIC_PORTC_PRIORITY_DEFAULT         CONFIG_FC7300_PORTC_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTDINTS
#  define NVIC_PORTD_PRIORITY_DEFAULT         CONFIG_FC7300_PORTD_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTEINTS
#  define NVIC_PORTE_PRIORITY_DEFAULT         CONFIG_FC7300_PORTE_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTFINTS
#  define NVIC_PORTF_PRIORITY_DEFAULT         CONFIG_FC7300_PORTF_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTGINTS
#  define NVIC_PORTG_PRIORITY_DEFAULT         CONFIG_FC7300_PORTG_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTHINTS
#  define NVIC_PORTH_PRIORITY_DEFAULT         CONFIG_FC7300_PORTH_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_PORTIINTS
#  define NVIC_PORTI_PRIORITY_DEFAULT         CONFIG_FC7300_PORTI_ISR_PRIORITY
#endif
#else
#  define NVIC_PORTA_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTB_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTC_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTD_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTE_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTF_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTG_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTH_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_PORTI_PRIORITY_DEFAULT         NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default TSTMP1 isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_TSTMP1
#  define NVIC_TSTMP1_PRIORITY_DEFAULT       CONFIG_FC7300_TSTMP1_ISR_PRIORITY
#endif
#else
#  define NVIC_TSTMP1_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default TSTMP2 isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_TSTMP2
#  define NVIC_TSTMP2_PRIORITY_DEFAULT       CONFIG_FC7300_TSTMP2_ISR_PRIORITY
#endif
#else
#  define NVIC_TSTMP2_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default TSTMP3 isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_TSTMP3
#  define NVIC_TSTMP3_PRIORITY_DEFAULT       CONFIG_FC7300_TSTMP3_ISR_PRIORITY
#endif
#else
#  define NVIC_TSTMP3_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default FCUART isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#  define NVIC_FCUART_PRIORITY_DEFAULT       0xc0
#else
#  define NVIC_FCUART_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default WATCHDOG0 isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_WATCHDOG0
#  define NVIC_WATCHDOG0_PRIORITY_DEFAULT    CONFIG_FC7300_WATCHDOG0_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_WATCHDOG1
#  define NVIC_WATCHDOG1_PRIORITY_DEFAULT    CONFIG_FC7300_WATCHDOG1_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_WATCHDOG2
#  define NVIC_WATCHDOG2_PRIORITY_DEFAULT    CONFIG_FC7300_WATCHDOG2_ISR_PRIORITY
#endif
#else
#  define NVIC_WATCHDOG0_PRIORITY_DEFAULT    NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_WATCHDOG1_PRIORITY_DEFAULT    NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_WATCHDOG2_PRIORITY_DEFAULT    NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default DMA isr priority */

#define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(X)  NVIC_DMA0_CHAN##X##_PRIORITY_DEFAULT
#define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(X)  NVIC_DMA1_CHAN##X##_PRIORITY_DEFAULT

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_DMA0_CHAN0_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(0)    CONFIG_FC7300_DMA0_CHAN0_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN1_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(1)    CONFIG_FC7300_DMA0_CHAN1_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN2_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(2)    CONFIG_FC7300_DMA0_CHAN2_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN3_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(3)    CONFIG_FC7300_DMA0_CHAN3_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN4_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(4)    CONFIG_FC7300_DMA0_CHAN4_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN5_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(5)    CONFIG_FC7300_DMA0_CHAN5_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN6_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(6)    CONFIG_FC7300_DMA0_CHAN6_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN7_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(7)    CONFIG_FC7300_DMA0_CHAN7_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN8_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(8)    CONFIG_FC7300_DMA0_CHAN8_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN9_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(9)    CONFIG_FC7300_DMA0_CHAN9_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN10_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(10)    CONFIG_FC7300_DMA0_CHAN10_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN11_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(11)    CONFIG_FC7300_DMA0_CHAN11_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN12_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(12)    CONFIG_FC7300_DMA0_CHAN12_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN13_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(13)    CONFIG_FC7300_DMA0_CHAN13_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN14_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(14)    CONFIG_FC7300_DMA0_CHAN14_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN15_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(15)    CONFIG_FC7300_DMA0_CHAN15_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN16_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(16)    CONFIG_FC7300_DMA0_CHAN16_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN17_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(17)    CONFIG_FC7300_DMA0_CHAN17_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN18_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(18)    CONFIG_FC7300_DMA0_CHAN18_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN19_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(19)    CONFIG_FC7300_DMA0_CHAN19_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN20_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(20)    CONFIG_FC7300_DMA0_CHAN20_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN21_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(21)    CONFIG_FC7300_DMA0_CHAN21_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN22_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(22)    CONFIG_FC7300_DMA0_CHAN22_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN23_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(23)    CONFIG_FC7300_DMA0_CHAN23_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN24_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(24)    CONFIG_FC7300_DMA0_CHAN24_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN25_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(25)    CONFIG_FC7300_DMA0_CHAN25_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN26_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(26)    CONFIG_FC7300_DMA0_CHAN26_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN27_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(27)    CONFIG_FC7300_DMA0_CHAN27_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN28_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(28)    CONFIG_FC7300_DMA0_CHAN28_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN29_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(29)    CONFIG_FC7300_DMA0_CHAN29_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN30_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(30)    CONFIG_FC7300_DMA0_CHAN30_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_CHAN31_ISR_PRIORITY
#  define NVIC_DMA0_CHANn_PRIORITY_DEFAULT(31)    CONFIG_FC7300_DMA0_CHAN31_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA0_ERROR_ISR_PRIORITY
#  define NVIC_DMA0_ERROR_PRIORITY_DEFAULT        CONFIG_FC7300_DMA0_ERROR_ISR_PRIORITY
#endif
#else
#  define NVIC_DMA0_CHAN0_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN1_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN2_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN3_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN4_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN5_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN6_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN7_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN8_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN9_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN10_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN11_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN12_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN13_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN14_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN15_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN16_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN17_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN18_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN19_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN20_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN21_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN22_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN23_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN24_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN25_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN26_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN27_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN28_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN29_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN30_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_CHAN31_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA0_ERROR_PRIORITY_DEFAULT  NVIC_SYSH_PRIORITY_DEFAULT
#endif

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined CONFIG_FC7300_DMA1_CHAN0_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(0)    CONFIG_FC7300_DMA1_CHAN0_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN1_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(1)    CONFIG_FC7300_DMA1_CHAN1_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN2_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(2)    CONFIG_FC7300_DMA1_CHAN2_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN3_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(3)    CONFIG_FC7300_DMA1_CHAN3_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN4_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(4)    CONFIG_FC7300_DMA1_CHAN4_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN5_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(5)    CONFIG_FC7300_DMA1_CHAN5_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN6_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(6)    CONFIG_FC7300_DMA1_CHAN6_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN7_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(7)    CONFIG_FC7300_DMA1_CHAN7_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN8_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(8)    CONFIG_FC7300_DMA1_CHAN8_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN9_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(9)    CONFIG_FC7300_DMA1_CHAN9_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN10_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(10)    CONFIG_FC7300_DMA1_CHAN10_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN11_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(11)    CONFIG_FC7300_DMA1_CHAN11_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN12_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(12)    CONFIG_FC7300_DMA1_CHAN12_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN13_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(13)    CONFIG_FC7300_DMA1_CHAN13_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN14_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(14)    CONFIG_FC7300_DMA1_CHAN14_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN15_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(15)    CONFIG_FC7300_DMA1_CHAN15_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN16_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(16)    CONFIG_FC7300_DMA1_CHAN16_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN17_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(17)    CONFIG_FC7300_DMA1_CHAN17_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN18_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(18)    CONFIG_FC7300_DMA1_CHAN18_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN19_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(19)    CONFIG_FC7300_DMA1_CHAN19_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN20_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(20)    CONFIG_FC7300_DMA1_CHAN20_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN21_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(21)    CONFIG_FC7300_DMA1_CHAN21_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN22_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(22)    CONFIG_FC7300_DMA1_CHAN22_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN23_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(23)    CONFIG_FC7300_DMA1_CHAN23_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN24_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(24)    CONFIG_FC7300_DMA1_CHAN24_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN25_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(25)    CONFIG_FC7300_DMA1_CHAN25_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN26_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(26)    CONFIG_FC7300_DMA1_CHAN26_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN27_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(27)    CONFIG_FC7300_DMA1_CHAN27_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN28_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(28)    CONFIG_FC7300_DMA1_CHAN28_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN29_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(29)    CONFIG_FC7300_DMA1_CHAN29_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN30_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(30)    CONFIG_FC7300_DMA1_CHAN30_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_CHAN31_ISR_PRIORITY
#  define NVIC_DMA1_CHANn_PRIORITY_DEFAULT(31)    CONFIG_FC7300_DMA1_CHAN31_ISR_PRIORITY
#endif
#if defined CONFIG_FC7300_DMA1_ERROR_ISR_PRIORITY
#  define NVIC_DMA1_ERROR_PRIORITY_DEFAULT        CONFIG_FC7300_DMA1_ERROR_ISR_PRIORITY
#endif
#else
#  define NVIC_DMA1_CHAN0_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN1_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN2_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN3_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN4_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN5_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN6_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN7_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN8_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN9_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN10_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN11_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN12_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN13_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN14_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN15_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN16_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN17_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN18_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN19_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN20_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN21_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN22_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN23_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN24_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN25_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN26_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN27_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN28_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN29_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN30_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_CHAN31_PRIORITY_DEFAULT NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_DMA1_ERROR_PRIORITY_DEFAULT  NVIC_SYSH_PRIORITY_DEFAULT
#endif

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#  define NVIC_ENET0_TX0_PRIORITY_DEFAULT   CONFIG_FC7300_ENET0_TX0_ISR_PRIORITY
#  define NVIC_ENET0_RX0_PRIORITY_DEFAULT   CONFIG_FC7300_ENET0_RX0_ISR_PRIORITY
#  define NVIC_ENET0_TX1_PRIORITY_DEFAULT   CONFIG_FC7300_ENET0_TX1_ISR_PRIORITY
#  define NVIC_ENET0_RX1_PRIORITY_DEFAULT   CONFIG_FC7300_ENET0_RX1_ISR_PRIORITY
#  define NVIC_ENET0_SYS_PRIORITY_DEFAULT   CONFIG_FC7300_ENET0_SYS_ISR_PRIORITY
#else
#  define NVIC_ENET0_TX0_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ENET0_RX0_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ENET0_TX1_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ENET0_RX1_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#  define NVIC_ENET0_SYS_PRIORITY_DEFAULT   NVIC_SYSH_PRIORITY_DEFAULT
#endif

/* Default RTC isr priority */

#ifdef CONFIG_ARCH_HIPRI_INTERRUPT
#if defined(CONFIG_FC7300_RTC)
#  define NVIC_RTC_PRIORITY_DEFAULT       CONFIG_FC7300_RTC_ISR_PRIORITY
#endif
#else
#  define NVIC_RTC_PRIORITY_DEFAULT       NVIC_SYSH_PRIORITY_DEFAULT
#endif
/****************************************************************************
 * Public Types
 ****************************************************************************/

/****************************************************************************
 * Public Data
 ****************************************************************************/

/****************************************************************************
 * Public Function Prototypes
 ****************************************************************************/

#endif /* __VENDOR_FLAGCHIP_CHIPS_FC7300_CHIP_H */
